version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  pgdata: